import { overviewTheme } from "@/utils/themes";
import { Container, ThemeProvider } from "@mui/material";
import React, { useEffect, useState } from "react";
import FramerContainer from "../../components/common/FramerContainer";
import Head from "next/head";
import { motion, useAnimate } from "framer-motion";
import {
  childAnimationController,
  rootAnimationController,
} from "@/utils/homeAnimationUtils";

const Home = () => {
  const [sectionInFocus, setSectionInFocus] = useState<string>();

  const [scope, sectionControls] = useAnimate();

  // useEffect(() => {
  //   const animationSequence = async () => {
  //     await sectionControls.start("moveIn");
  //     await sectionControls.start("pop");
  //   };
  //   animationSequence();
  // }, [sectionControls]);

  return (
    <>
      <Head>
        <title>Portfolio | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={overviewTheme}>
        <Container id="layout-root" component={motion.main} disableGutters>
          <FramerContainer
            id="layout-caption-skills"
            onClick={(evt) => setSectionInFocus(evt.currentTarget.id)}
            initial={"initial"}
            animate={
              sectionInFocus === "layout-caption-skills"
                ? "sectionFocus"
                : ["moveIn", "pop"]
            }
            variants={childAnimationController}
          ></FramerContainer>
          <FramerContainer
            id="layout-profile-socials"
            onClick={(evt) => setSectionInFocus(evt.currentTarget.id)}
          ></FramerContainer>
          <FramerContainer id="layout-projects"></FramerContainer>
          <FramerContainer id="layout-about"></FramerContainer>
        </Container>
      </ThemeProvider>
    </>
  );
};

export default Home;
